//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 12:22:02 PM BST 
//


package es.ull.cyc.simulation.bind;

import javax.xml.bind.annotation.XmlEnum;
import es.ull.cyc.simulation.bind.FlowType;


/**
 * <p>Java class for FlowType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FlowType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SINGLE"/>
 *     &lt;enumeration value="DECISION"/>
 *     &lt;enumeration value="SEQUENCE"/>
 *     &lt;enumeration value="SIMULTANEOUS"/>
 *     &lt;enumeration value="PACKED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum FlowType {

    DECISION,
    PACKED,
    SEQUENCE,
    SIMULTANEOUS,
    SINGLE;

    public String value() {
        return name();
    }

    public FlowType fromValue(String v) {
        return valueOf(v);
    }

}
