//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 12:22:02 PM BST 
//


package es.ull.cyc.simulation.bind;

import javax.xml.bind.annotation.XmlRegistry;
import es.ull.cyc.simulation.bind.Activity;
import es.ull.cyc.simulation.bind.Activity.WorkGroup;
import es.ull.cyc.simulation.bind.Cycle;
import es.ull.cyc.simulation.bind.Experiment;
import es.ull.cyc.simulation.bind.Flow;
import es.ull.cyc.simulation.bind.FlowExtension;
import es.ull.cyc.simulation.bind.Generation;
import es.ull.cyc.simulation.bind.Generator;
import es.ull.cyc.simulation.bind.Model;
import es.ull.cyc.simulation.bind.ObjectFactory;
import es.ull.cyc.simulation.bind.ProbTree;
import es.ull.cyc.simulation.bind.RandomNumber;
import es.ull.cyc.simulation.bind.Resource;
import es.ull.cyc.simulation.bind.Resource.TimeTable;
import es.ull.cyc.simulation.bind.Resource.TimeTable.Dur;
import es.ull.cyc.simulation.bind.ResultClass;
import es.ull.cyc.simulation.bind.ResultClass.Param;
import es.ull.cyc.simulation.bind.Scenario;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.ull.cyc.simulation.bind package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.ull.cyc.simulation.bind
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProbTree }
     * 
     */
    public ProbTree createProbTree() {
        return new ProbTree();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link Generation }
     * 
     */
    public Generation createGeneration() {
        return new Generation();
    }

    /**
     * Create an instance of {@link Generator }
     * 
     */
    public Generator createGenerator() {
        return new Generator();
    }

    /**
     * Create an instance of {@link es.ull.cyc.simulation.bind.Activity.WorkGroup.ResourceType }
     * 
     */
    public es.ull.cyc.simulation.bind.Activity.WorkGroup.ResourceType createActivityWorkGroupResourceType() {
        return new es.ull.cyc.simulation.bind.Activity.WorkGroup.ResourceType();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createResultClassParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link RandomNumber }
     * 
     */
    public RandomNumber createRandomNumber() {
        return new RandomNumber();
    }

    /**
     * Create an instance of {@link es.ull.cyc.simulation.bind.ResourceType }
     * 
     */
    public es.ull.cyc.simulation.bind.ResourceType createResourceType() {
        return new es.ull.cyc.simulation.bind.ResourceType();
    }

    /**
     * Create an instance of {@link ResultClass }
     * 
     */
    public ResultClass createResultClass() {
        return new ResultClass();
    }

    /**
     * Create an instance of {@link TimeTable }
     * 
     */
    public TimeTable createResourceTimeTable() {
        return new TimeTable();
    }

    /**
     * Create an instance of {@link Flow }
     * 
     */
    public Flow createFlow() {
        return new Flow();
    }

    /**
     * Create an instance of {@link WorkGroup }
     * 
     */
    public WorkGroup createActivityWorkGroup() {
        return new WorkGroup();
    }

    /**
     * Create an instance of {@link FlowExtension }
     * 
     */
    public FlowExtension createFlowExtension() {
        return new FlowExtension();
    }

    /**
     * Create an instance of {@link Dur }
     * 
     */
    public Dur createResourceTimeTableDur() {
        return new Dur();
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link Experiment }
     * 
     */
    public Experiment createExperiment() {
        return new Experiment();
    }

    /**
     * Create an instance of {@link Cycle }
     * 
     */
    public Cycle createCycle() {
        return new Cycle();
    }

}
