//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 10:31:31 AM BST 
//


package es.ull.isaatc.simulation.listener.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.ull.isaatc.simulation.listener.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.ull.isaatc.simulation.listener.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ElementTypeTimeListener.Et.WorkTime }
     * 
     */
    public ElementTypeTimeListener.Et.WorkTime createElementTypeTimeListenerEtWorkTime() {
        return new ElementTypeTimeListener.Et.WorkTime();
    }

    /**
     * Create an instance of {@link ResourceStdUsageListener.Resource.Available }
     * 
     */
    public ResourceStdUsageListener.Resource.Available createResourceStdUsageListenerResourceAvailable() {
        return new ResourceStdUsageListener.Resource.Available();
    }

    /**
     * Create an instance of {@link SelectableActivityListener.Activity }
     * 
     */
    public SelectableActivityListener.Activity createSelectableActivityListenerActivity() {
        return new SelectableActivityListener.Activity();
    }

    /**
     * Create an instance of {@link ResourceStdUsageListener.Resource.Usage.Rt }
     * 
     */
    public ResourceStdUsageListener.Resource.Usage.Rt createResourceStdUsageListenerResourceUsageRt() {
        return new ResourceStdUsageListener.Resource.Usage.Rt();
    }

    /**
     * Create an instance of {@link SelectableActivityListener }
     * 
     */
    public SelectableActivityListener createSelectableActivityListener() {
        return new SelectableActivityListener();
    }

    /**
     * Create an instance of {@link SimulationListener }
     * 
     */
    public SimulationListener createSimulationListener() {
        return new SimulationListener();
    }

    /**
     * Create an instance of {@link ElementTypeTimeListener.Et }
     * 
     */
    public ElementTypeTimeListener.Et createElementTypeTimeListenerEt() {
        return new ElementTypeTimeListener.Et();
    }

    /**
     * Create an instance of {@link ElementTypeTimeListener }
     * 
     */
    public ElementTypeTimeListener createElementTypeTimeListener() {
        return new ElementTypeTimeListener();
    }

    /**
     * Create an instance of {@link SelectableActivityListener.Activity.ActQueue }
     * 
     */
    public SelectableActivityListener.Activity.ActQueue createSelectableActivityListenerActivityActQueue() {
        return new SelectableActivityListener.Activity.ActQueue();
    }

    /**
     * Create an instance of {@link SelectableActivityTimeListener }
     * 
     */
    public SelectableActivityTimeListener createSelectableActivityTimeListener() {
        return new SelectableActivityTimeListener();
    }

    /**
     * Create an instance of {@link ResourceStdUsageListener.Resource }
     * 
     */
    public ResourceStdUsageListener.Resource createResourceStdUsageListenerResource() {
        return new ResourceStdUsageListener.Resource();
    }

    /**
     * Create an instance of {@link ResourceStdUsageListener }
     * 
     */
    public ResourceStdUsageListener createResourceStdUsageListener() {
        return new ResourceStdUsageListener();
    }

    /**
     * Create an instance of {@link ResourceStdUsageListener.Resource.Usage }
     * 
     */
    public ResourceStdUsageListener.Resource.Usage createResourceStdUsageListenerResourceUsage() {
        return new ResourceStdUsageListener.Resource.Usage();
    }

    /**
     * Create an instance of {@link ElementStartFinishListener }
     * 
     */
    public ElementStartFinishListener createElementStartFinishListener() {
        return new ElementStartFinishListener();
    }

    /**
     * Create an instance of {@link ActivityListener.Activity }
     * 
     */
    public ActivityListener.Activity createActivityListenerActivity() {
        return new ActivityListener.Activity();
    }

    /**
     * Create an instance of {@link ListenerInfo.AverageResults }
     * 
     */
    public ListenerInfo.AverageResults createListenerInfoAverageResults() {
        return new ListenerInfo.AverageResults();
    }

    /**
     * Create an instance of {@link ActivityListener.Activity.ActQueue }
     * 
     */
    public ActivityListener.Activity.ActQueue createActivityListenerActivityActQueue() {
        return new ActivityListener.Activity.ActQueue();
    }

    /**
     * Create an instance of {@link SelectableActivityListener.Activity.ActPerformed }
     * 
     */
    public SelectableActivityListener.Activity.ActPerformed createSelectableActivityListenerActivityActPerformed() {
        return new SelectableActivityListener.Activity.ActPerformed();
    }

    /**
     * Create an instance of {@link SimulationTimeListener }
     * 
     */
    public SimulationTimeListener createSimulationTimeListener() {
        return new SimulationTimeListener();
    }

    /**
     * Create an instance of {@link ElementTypeTimeListener.Et.Finished }
     * 
     */
    public ElementTypeTimeListener.Et.Finished createElementTypeTimeListenerEtFinished() {
        return new ElementTypeTimeListener.Et.Finished();
    }

    /**
     * Create an instance of {@link ActivityTimeListener }
     * 
     */
    public ActivityTimeListener createActivityTimeListener() {
        return new ActivityTimeListener();
    }

    /**
     * Create an instance of {@link ActivityListener.Activity.ActPerformed }
     * 
     */
    public ActivityListener.Activity.ActPerformed createActivityListenerActivityActPerformed() {
        return new ActivityListener.Activity.ActPerformed();
    }

    /**
     * Create an instance of {@link ListenerInfo.SimulationResults }
     * 
     */
    public ListenerInfo.SimulationResults createListenerInfoSimulationResults() {
        return new ListenerInfo.SimulationResults();
    }

    /**
     * Create an instance of {@link ActivityTimeListener.Activity }
     * 
     */
    public ActivityTimeListener.Activity createActivityTimeListenerActivity() {
        return new ActivityTimeListener.Activity();
    }

    /**
     * Create an instance of {@link ElementStartFinishListener.Created }
     * 
     */
    public ElementStartFinishListener.Created createElementStartFinishListenerCreated() {
        return new ElementStartFinishListener.Created();
    }

    /**
     * Create an instance of {@link ActivityListener }
     * 
     */
    public ActivityListener createActivityListener() {
        return new ActivityListener();
    }

    /**
     * Create an instance of {@link ElementStartFinishListener.Finished }
     * 
     */
    public ElementStartFinishListener.Finished createElementStartFinishListenerFinished() {
        return new ElementStartFinishListener.Finished();
    }

    /**
     * Create an instance of {@link SelectableActivityTimeListener.Activity }
     * 
     */
    public SelectableActivityTimeListener.Activity createSelectableActivityTimeListenerActivity() {
        return new SelectableActivityTimeListener.Activity();
    }

    /**
     * Create an instance of {@link ElementTypeTimeListener.Et.Created }
     * 
     */
    public ElementTypeTimeListener.Et.Created createElementTypeTimeListenerEtCreated() {
        return new ElementTypeTimeListener.Et.Created();
    }

    /**
     * Create an instance of {@link PeriodicListener }
     * 
     */
    public PeriodicListener createPeriodicListener() {
        return new PeriodicListener();
    }

    /**
     * Create an instance of {@link ResourceStdUsageListener.Resource.Available.Rt }
     * 
     */
    public ResourceStdUsageListener.Resource.Available.Rt createResourceStdUsageListenerResourceAvailableRt() {
        return new ResourceStdUsageListener.Resource.Available.Rt();
    }

    /**
     * Create an instance of {@link ListenerInfo }
     * 
     */
    public ListenerInfo createListenerInfo() {
        return new ListenerInfo();
    }

}
