//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 10:31:31 AM BST 
//


package es.ull.isaatc.simulation.listener.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimulationTimeListener complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimulationTimeListener">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/SimulationListener}SimulationListener">
 *       &lt;sequence>
 *         &lt;element name="simulationTime" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimulationTimeListener", propOrder = {
    "simulationTime"
})
public class SimulationTimeListener
    extends SimulationListener
{

    protected double simulationTime;

    /**
     * Gets the value of the simulationTime property.
     * 
     */
    public double getSimulationTime() {
        return simulationTime;
    }

    /**
     * Sets the value of the simulationTime property.
     * 
     */
    public void setSimulationTime(double value) {
        this.simulationTime = value;
    }

}
