//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 12:22:02 PM BST 
//


package es.ull.cyc.simulation.bind;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import es.ull.cyc.simulation.bind.Distribution;
import es.ull.cyc.simulation.bind.RandomNumber;


/**
 * <p>Java class for RandomNumber complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RandomNumber">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dist" type="{}Distribution"/>
 *         &lt;element name="p1" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="p2" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="p3" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "RandomNumber", propOrder = {
    "dist",
    "p1",
    "p2",
    "p3"
})
public class RandomNumber {

    protected Distribution dist;
    @XmlElement(type = Double.class)
    protected double p1;
    @XmlElement(type = Double.class)
    protected double p2;
    @XmlElement(type = Double.class)
    protected double p3;

    /**
     * Gets the value of the dist property.
     * 
     * @return
     *     possible object is
     *     {@link Distribution }
     *     
     */
    public Distribution getDist() {
        return dist;
    }

    /**
     * Sets the value of the dist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Distribution }
     *     
     */
    public void setDist(Distribution value) {
        this.dist = value;
    }

    /**
     * Gets the value of the p1 property.
     * 
     */
    public double getP1() {
        return p1;
    }

    /**
     * Sets the value of the p1 property.
     * 
     */
    public void setP1(double value) {
        this.p1 = value;
    }

    /**
     * Gets the value of the p2 property.
     * 
     */
    public double getP2() {
        return p2;
    }

    /**
     * Sets the value of the p2 property.
     * 
     */
    public void setP2(double value) {
        this.p2 = value;
    }

    /**
     * Gets the value of the p3 property.
     * 
     */
    public double getP3() {
        return p3;
    }

    /**
     * Sets the value of the p3 property.
     * 
     */
    public void setP3(double value) {
        this.p3 = value;
    }

}
