//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 09:55:05 AM BST 
//


package es.ull.isaatc.simulation.xml;

import javax.xml.bind.annotation.XmlEnum;
import es.ull.isaatc.simulation.xml.CommonFreq;


/**
 * <p>Java class for CommonFreq.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CommonFreq">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="YEAR"/>
 *     &lt;enumeration value="MONTH"/>
 *     &lt;enumeration value="DAY"/>
 *     &lt;enumeration value="HOUR"/>
 *     &lt;enumeration value="MINUTE"/>
 *     &lt;enumeration value="SECOND"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum CommonFreq {

    DAY,
    HOUR,
    MINUTE,
    MONTH,
    SECOND,
    YEAR;

    public String value() {
        return name();
    }

    public CommonFreq fromValue(String v) {
        return valueOf(v);
    }

}
