//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.18 at 06:31:27 PM BST 
//

package es.ull.isaatc.simulation.xml;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import es.ull.isaatc.simulation.xml.CommonFreq;
import es.ull.isaatc.simulation.xml.Cycle;
import es.ull.isaatc.simulation.xml.RandomNumber;

/**
 * <p>
 * Java class for Cycle complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 *   &lt;complexType name=&quot;Cycle&quot;&gt;
 *     &lt;complexContent&gt;
 *       &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *         &lt;sequence&gt;
 *           &lt;element name=&quot;timeUnit&quot; type=&quot;{}CommonFreq&quot;/&gt;
 *           &lt;element name=&quot;startTs&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}double&quot;/&gt;
 *           &lt;choice&gt;
 *             &lt;element name=&quot;iterations&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *             &lt;element name=&quot;endTs&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}double&quot;/&gt;
 *           &lt;/choice&gt;
 *           &lt;element name=&quot;period&quot; type=&quot;{}RandomNumber&quot;/&gt;
 *           &lt;element name=&quot;subCycle&quot; type=&quot;{}Cycle&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/restriction&gt;
 *     &lt;/complexContent&gt;
 *   &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "Cycle", propOrder = { "timeUnit", "startTs", "iterations",
	"endTs", "period", "subCycle" })
public class Cycle {

    protected CommonFreq timeUnit;

    @XmlElement(type = Double.class)
    protected double startTs;

    protected Integer iterations;

    protected Double endTs;

    protected RandomNumber period;

    protected Cycle subCycle;

    /**
         * Gets the value of the timeUnit property.
         * 
         * @return possible object is {@link CommonFreq }
         * 
         */
    public CommonFreq getTimeUnit() {
	return timeUnit;
    }

    /**
         * Sets the value of the timeUnit property.
         * 
         * @param value
         *                allowed object is {@link CommonFreq }
         * 
         */
    public void setTimeUnit(CommonFreq value) {
	this.timeUnit = value;
    }

    /**
         * Gets the value of the startTs property.
         * 
         */
    public double getStartTs() {
	return startTs;
    }

    /**
         * Sets the value of the startTs property.
         * 
         */
    public void setStartTs(double value) {
	this.startTs = value;
    }

    /**
         * Gets the value of the iterations property.
         * 
         * @return possible object is {@link Integer }
         * 
         */
    public Integer getIterations() {
	return iterations;
    }

    /**
         * Sets the value of the iterations property.
         * 
         * @param value
         *                allowed object is {@link Integer }
         * 
         */
    public void setIterations(Integer value) {
	this.iterations = value;
    }

    /**
         * Gets the value of the endTs property.
         * 
         * @return possible object is {@link Double }
         * 
         */
    public Double getEndTs() {
	return endTs;
    }

    /**
         * Sets the value of the endTs property.
         * 
         * @param value
         *                allowed object is {@link Double }
         * 
         */
    public void setEndTs(Double value) {
	this.endTs = value;
    }

    /**
         * Gets the value of the period property.
         * 
         * @return possible object is {@link RandomNumber }
         * 
         */
    public RandomNumber getPeriod() {
	return period;
    }

    /**
         * Sets the value of the period property.
         * 
         * @param value
         *                allowed object is {@link RandomNumber }
         * 
         */
    public void setPeriod(RandomNumber value) {
	this.period = value;
    }

    /**
         * Gets the value of the subCycle property.
         * 
         * @return possible object is {@link Cycle }
         * 
         */
    public Cycle getSubCycle() {
	return subCycle;
    }

    /**
         * Sets the value of the subCycle property.
         * 
         * @param value
         *                allowed object is {@link Cycle }
         * 
         */
    public void setSubCycle(Cycle value) {
	this.subCycle = value;
    }

}
