//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.09 at 04:59:55 PM BST 
//

package es.ull.isaatc.simulation.xml;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import es.ull.isaatc.simulation.xml.ExitFlow;
import es.ull.isaatc.simulation.xml.Flow;

/**
 * <p>
 * Java class for ExitFlow complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 *  &lt;complexType name=&quot;ExitFlow&quot;&gt;
 *    &lt;complexContent&gt;
 *      &lt;extension base=&quot;{}Flow&quot;&gt;
 *      &lt;/extension&gt;
 *    &lt;/complexContent&gt;
 *  &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "ExitFlow")
public class ExitFlow extends Flow {
	
}
