//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.18 at 06:31:27 PM BST 
//

package es.ull.isaatc.simulation.xml;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import es.ull.isaatc.simulation.xml.Flow;
import es.ull.isaatc.simulation.xml.RandomNumber;

/**
 * <p>
 * Java class for Flow complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 *   &lt;complexType name=&quot;Flow&quot;&gt;
 *     &lt;complexContent&gt;
 *       &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *         &lt;sequence&gt;
 *           &lt;element name=&quot;iterations&quot; type=&quot;{}RandomNumber&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;/sequence&gt;
 *         &lt;attribute name=&quot;id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *       &lt;/restriction&gt;
 *     &lt;/complexContent&gt;
 *   &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "Flow", propOrder = { "iterations" })
public class Flow {

    protected RandomNumber iterations;

    @XmlAttribute(required = true)
    protected int id;

    /**
         * Gets the value of the iterations property.
         * 
         * @return possible object is {@link RandomNumber }
         * 
         */
    public RandomNumber getIterations() {
	return iterations;
    }

    /**
         * Sets the value of the iterations property.
         * 
         * @param value
         *                allowed object is {@link RandomNumber }
         * 
         */
    public void setIterations(RandomNumber value) {
	this.iterations = value;
    }

    /**
         * Gets the value of the id property.
         * 
         */
    public int getId() {
	return id;
    }

    /**
         * Sets the value of the id property.
         * 
         */
    public void setId(int value) {
	this.id = value;
    }

}
