//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.12 at 03:20:00 PM BST 
//


package es.ull.isaatc.simulation.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FunctionChoice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FunctionChoice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="constant" type="{}ConstantFunction"/>
 *         &lt;element name="poly" type="{}PolyFunction"/>
 *         &lt;element name="random" type="{}RandomNumber"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FunctionChoice", propOrder = {
    "constant",
    "poly",
    "random"
})
public class FunctionChoice {

    protected ConstantFunction constant;
    protected PolyFunction poly;
    protected RandomNumber random;

    /**
     * Gets the value of the constant property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantFunction }
     *     
     */
    public ConstantFunction getConstant() {
        return constant;
    }

    /**
     * Sets the value of the constant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantFunction }
     *     
     */
    public void setConstant(ConstantFunction value) {
        this.constant = value;
    }

    /**
     * Gets the value of the poly property.
     * 
     * @return
     *     possible object is
     *     {@link PolyFunction }
     *     
     */
    public PolyFunction getPoly() {
        return poly;
    }

    /**
     * Sets the value of the poly property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolyFunction }
     *     
     */
    public void setPoly(PolyFunction value) {
        this.poly = value;
    }

    /**
     * Gets the value of the random property.
     * 
     * @return
     *     possible object is
     *     {@link RandomNumber }
     *     
     */
    public RandomNumber getRandom() {
        return random;
    }

    /**
     * Sets the value of the random property.
     * 
     * @param value
     *     allowed object is
     *     {@link RandomNumber }
     *     
     */
    public void setRandom(RandomNumber value) {
        this.random = value;
    }

}
