//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.09 at 04:59:55 PM BST 
//

package es.ull.isaatc.simulation.xml;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import es.ull.isaatc.simulation.xml.Generation;
import es.ull.isaatc.simulation.xml.ProbTree;
import es.ull.isaatc.simulation.xml.RandomNumber;

/**
 * <p>
 * Java class for Generation complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 *  &lt;complexType name=&quot;Generation&quot;&gt;
 *    &lt;complexContent&gt;
 *      &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *        &lt;sequence&gt;
 *          &lt;element name=&quot;nElem&quot; type=&quot;{}RandomNumber&quot;/&gt;
 *          &lt;element name=&quot;probTree&quot; type=&quot;{}ProbTree&quot;/&gt;
 *        &lt;/sequence&gt;
 *      &lt;/restriction&gt;
 *    &lt;/complexContent&gt;
 *  &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "Generation", propOrder = { "nElem", "probTree" })
public class Generation {
	
	
	protected RandomNumber nElem;
	
	protected ProbTree probTree;
	
	
	
	
	/**
	 * Gets the value of the nElem property.
	 * 
	 * @return possible object is {@link RandomNumber }
	 */
	public RandomNumber getNElem() {

		return nElem;
	}
	
	
	
	/**
	 * Sets the value of the nElem property.
	 * 
	 * @param value
	 *          allowed object is {@link RandomNumber }
	 */
	public void setNElem(RandomNumber value) {

		this.nElem = value;
	}
	
	
	
	/**
	 * Gets the value of the probTree property.
	 * 
	 * @return possible object is {@link ProbTree }
	 */
	public ProbTree getProbTree() {

		return probTree;
	}
	
	
	
	/**
	 * Sets the value of the probTree property.
	 * 
	 * @param value
	 *          allowed object is {@link ProbTree }
	 */
	public void setProbTree(ProbTree value) {

		this.probTree = value;
	}
	
}
