//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.26 at 12:20:59 PM BST 
//


package es.ull.isaatc.simulation.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Listeners complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Listeners">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="activityListener" type="{}ActivityListener"/>
 *           &lt;element name="activityTimeListener" type="{}ActivityTimeListener"/>
 *           &lt;element name="elementStartFinishListener" type="{}ElementStartFinishListener"/>
 *           &lt;element name="elementTypeTimeListener" type="{}ElementTypeTimeListener"/>
 *           &lt;element name="resourceStdUsageListener" type="{}ResourceStdUsageListener"/>
 *           &lt;element name="selectableActivityListener" type="{}SelectableActivityListener"/>
 *           &lt;element name="selectableActivityTimeListener" type="{}SelectableActivityTimeListener"/>
 *           &lt;element name="simulationTimeListener" type="{}SimulationTimeListener"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Listeners", propOrder = {
    "activityListenerOrActivityTimeListenerOrElementStartFinishListener"
})
public class Listeners {

    @XmlElements({
        @XmlElement(name = "activityListener", type = ActivityListener.class),
        @XmlElement(name = "activityTimeListener", type = ActivityTimeListener.class),
        @XmlElement(name = "elementStartFinishListener", type = ElementStartFinishListener.class),
        @XmlElement(name = "resourceStdUsageListener", type = ResourceStdUsageListener.class),
        @XmlElement(name = "simulationTimeListener", type = SimulationTimeListener.class),
        @XmlElement(name = "selectableActivityTimeListener", type = SelectableActivityTimeListener.class),
        @XmlElement(name = "elementTypeTimeListener", type = ElementTypeTimeListener.class),
        @XmlElement(name = "selectableActivityListener", type = SelectableActivityListener.class)
    })
    protected List<ListenerDescription> activityListenerOrActivityTimeListenerOrElementStartFinishListener;

    /**
     * Gets the value of the activityListenerOrActivityTimeListenerOrElementStartFinishListener property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activityListenerOrActivityTimeListenerOrElementStartFinishListener property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivityListenerOrActivityTimeListenerOrElementStartFinishListener().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActivityListener }
     * {@link ActivityTimeListener }
     * {@link ElementStartFinishListener }
     * {@link ResourceStdUsageListener }
     * {@link SimulationTimeListener }
     * {@link SelectableActivityTimeListener }
     * {@link ElementTypeTimeListener }
     * {@link SelectableActivityListener }
     * 
     * 
     */
    public List<ListenerDescription> getActivityListenerOrActivityTimeListenerOrElementStartFinishListener() {
        if (activityListenerOrActivityTimeListenerOrElementStartFinishListener == null) {
            activityListenerOrActivityTimeListenerOrElementStartFinishListener = new ArrayList<ListenerDescription>();
        }
        return this.activityListenerOrActivityTimeListenerOrElementStartFinishListener;
    }

}
