//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b01-EA2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.06 at 06:25:30 PM BST 
//


package es.ull.isaatc.simulation.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.ull.isaatc.simulation.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.ull.isaatc.simulation.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Generator }
     * 
     */
    public Generator createGenerator() {
        return new Generator();
    }

    /**
     * Create an instance of {@link SequenceFlow }
     * 
     */
    public SequenceFlow createSequenceFlow() {
        return new SequenceFlow();
    }

    /**
     * Create an instance of {@link SimultaneousFlow }
     * 
     */
    public SimultaneousFlow createSimultaneousFlow() {
        return new SimultaneousFlow();
    }

    /**
     * Create an instance of {@link ElementTypeTimeListener }
     * 
     */
    public ElementTypeTimeListener createElementTypeTimeListener() {
        return new ElementTypeTimeListener();
    }

    /**
     * Create an instance of {@link SimulationTimeListener }
     * 
     */
    public SimulationTimeListener createSimulationTimeListener() {
        return new SimulationTimeListener();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link FlowChoice }
     * 
     */
    public FlowChoice createFlowChoice() {
        return new FlowChoice();
    }

    /**
     * Create an instance of {@link Cycle }
     * 
     */
    public Cycle createCycle() {
        return new Cycle();
    }

    /**
     * Create an instance of {@link PackageFlow }
     * 
     */
    public PackageFlow createPackageFlow() {
        return new PackageFlow();
    }

    /**
     * Create an instance of {@link RootFlow }
     * 
     */
    public RootFlow createRootFlow() {
        return new RootFlow();
    }

    /**
     * Create an instance of {@link TimeFunction }
     * 
     */
    public TimeFunction createTimeFunction() {
        return new TimeFunction();
    }

    /**
     * Create an instance of {@link PeriodicListener }
     * 
     */
    public PeriodicListener createPeriodicListener() {
        return new PeriodicListener();
    }

    /**
     * Create an instance of {@link SingleFlow }
     * 
     */
    public SingleFlow createSingleFlow() {
        return new SingleFlow();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link Activity.WorkGroup }
     * 
     */
    public Activity.WorkGroup createActivityWorkGroup() {
        return new Activity.WorkGroup();
    }

    /**
     * Create an instance of {@link Listeners }
     * 
     */
    public Listeners createListeners() {
        return new Listeners();
    }

    /**
     * Create an instance of {@link FunctionChoice }
     * 
     */
    public FunctionChoice createFunctionChoice() {
        return new FunctionChoice();
    }

    /**
     * Create an instance of {@link DecisionFlow }
     * 
     */
    public DecisionFlow createDecisionFlow() {
        return new DecisionFlow();
    }

    /**
     * Create an instance of {@link SelectableActivityListener }
     * 
     */
    public SelectableActivityListener createSelectableActivityListener() {
        return new SelectableActivityListener();
    }

    /**
     * Create an instance of {@link ClassReference.Param }
     * 
     */
    public ClassReference.Param createClassReferenceParam() {
        return new ClassReference.Param();
    }

    /**
     * Create an instance of {@link PolyFunction }
     * 
     */
    public PolyFunction createPolyFunction() {
        return new PolyFunction();
    }

    /**
     * Create an instance of {@link es.ull.isaatc.simulation.xml.WorkGroup }
     * 
     */
    public es.ull.isaatc.simulation.xml.WorkGroup createWorkGroup() {
        return new es.ull.isaatc.simulation.xml.WorkGroup();
    }

    /**
     * Create an instance of {@link TypeFlow }
     * 
     */
    public TypeFlow createTypeFlow() {
        return new TypeFlow();
    }

    /**
     * Create an instance of {@link ComponentRef }
     * 
     */
    public ComponentRef createComponentRef() {
        return new ComponentRef();
    }

    /**
     * Create an instance of {@link Experiment.EndTs }
     * 
     */
    public Experiment.EndTs createExperimentEndTs() {
        return new Experiment.EndTs();
    }

    /**
     * Create an instance of {@link Resource.TimeTable.Dur }
     * 
     */
    public Resource.TimeTable.Dur createResourceTimeTableDur() {
        return new Resource.TimeTable.Dur();
    }

    /**
     * Create an instance of {@link DescComponent }
     * 
     */
    public DescComponent createDescComponent() {
        return new DescComponent();
    }

    /**
     * Create an instance of {@link Vector }
     * 
     */
    public Vector createVector() {
        return new Vector();
    }

    /**
     * Create an instance of {@link ElementType }
     * 
     */
    public ElementType createElementType() {
        return new ElementType();
    }

    /**
     * Create an instance of {@link Experiment.StartTs }
     * 
     */
    public Experiment.StartTs createExperimentStartTs() {
        return new Experiment.StartTs();
    }

    /**
     * Create an instance of {@link TypeBranch }
     * 
     */
    public TypeBranch createTypeBranch() {
        return new TypeBranch();
    }

    /**
     * Create an instance of {@link SelectableActivityTimeListener }
     * 
     */
    public SelectableActivityTimeListener createSelectableActivityTimeListener() {
        return new SelectableActivityTimeListener();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link RandomNumber }
     * 
     */
    public RandomNumber createRandomNumber() {
        return new RandomNumber();
    }

    /**
     * Create an instance of {@link ActivityListener }
     * 
     */
    public ActivityListener createActivityListener() {
        return new ActivityListener();
    }

    /**
     * Create an instance of {@link Resource.TimeTable }
     * 
     */
    public Resource.TimeTable createResourceTimeTable() {
        return new Resource.TimeTable();
    }

    /**
     * Create an instance of {@link Flow }
     * 
     */
    public Flow createFlow() {
        return new Flow();
    }

    /**
     * Create an instance of {@link ExitFlow }
     * 
     */
    public ExitFlow createExitFlow() {
        return new ExitFlow();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link es.ull.isaatc.simulation.xml.WorkGroup.Role }
     * 
     */
    public es.ull.isaatc.simulation.xml.WorkGroup.Role createWorkGroupRole() {
        return new es.ull.isaatc.simulation.xml.WorkGroup.Role();
    }

    /**
     * Create an instance of {@link ClassReference }
     * 
     */
    public ClassReference createClassReference() {
        return new ClassReference();
    }

    /**
     * Create an instance of {@link DecisionOption }
     * 
     */
    public DecisionOption createDecisionOption() {
        return new DecisionOption();
    }

    /**
     * Create an instance of {@link ConstantFunction }
     * 
     */
    public ConstantFunction createConstantFunction() {
        return new ConstantFunction();
    }

    /**
     * Create an instance of {@link BaseComponent }
     * 
     */
    public BaseComponent createBaseComponent() {
        return new BaseComponent();
    }

    /**
     * Create an instance of {@link ResourceStdUsageListener }
     * 
     */
    public ResourceStdUsageListener createResourceStdUsageListener() {
        return new ResourceStdUsageListener();
    }

    /**
     * Create an instance of {@link ProbTree }
     * 
     */
    public ProbTree createProbTree() {
        return new ProbTree();
    }

    /**
     * Create an instance of {@link Experiment }
     * 
     */
    public Experiment createExperiment() {
        return new Experiment();
    }

    /**
     * Create an instance of {@link ListenerDescription }
     * 
     */
    public ListenerDescription createListenerDescription() {
        return new ListenerDescription();
    }

    /**
     * Create an instance of {@link ElementStartFinishListener }
     * 
     */
    public ElementStartFinishListener createElementStartFinishListener() {
        return new ElementStartFinishListener();
    }

    /**
     * Create an instance of {@link Generation }
     * 
     */
    public Generation createGeneration() {
        return new Generation();
    }

    /**
     * Create an instance of {@link ActivityTimeListener }
     * 
     */
    public ActivityTimeListener createActivityTimeListener() {
        return new ActivityTimeListener();
    }

}
