//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.23 at 01:07:00 PM GMT 
//


package es.ull.isaatc.simulation.xml;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import es.ull.isaatc.simulation.xml.ComponentRef;
import es.ull.isaatc.simulation.xml.Flow;
import es.ull.isaatc.simulation.xml.PackageFlow;


/**
 * <p>Java class for PackageFlow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageFlow">
 *   &lt;complexContent>
 *     &lt;extension base="{}Flow">
 *       &lt;sequence>
 *         &lt;element name="rootFlow_ref" type="{}ComponentRef"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "PackageFlow", propOrder = {
    "rootFlowRef"
})
public class PackageFlow
    extends Flow
{

    @XmlElement(name = "rootFlow_ref")
    protected ComponentRef rootFlowRef;

    /**
     * Gets the value of the rootFlowRef property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentRef }
     *     
     */
    public ComponentRef getRootFlowRef() {
        return rootFlowRef;
    }

    /**
     * Sets the value of the rootFlowRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentRef }
     *     
     */
    public void setRootFlowRef(ComponentRef value) {
        this.rootFlowRef = value;
    }

}
