//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.09 at 04:59:55 PM BST 
//

package es.ull.isaatc.simulation.xml;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import es.ull.isaatc.simulation.xml.ResourceType;

/**
 * <p>
 * Java class for ResourceType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 *  &lt;complexType name=&quot;ResourceType&quot;&gt;
 *    &lt;complexContent&gt;
 *      &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *        &lt;sequence&gt;
 *          &lt;element name=&quot;description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *        &lt;/sequence&gt;
 *        &lt;attribute name=&quot;id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *      &lt;/restriction&gt;
 *    &lt;/complexContent&gt;
 *  &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "ResourceType", propOrder = { "description" })
public class ResourceType {
	
	
	protected String description;
	
	@XmlAttribute(required = true)
	protected int id;
	
	
	
	
	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDescription() {

		return description;
	}
	
	
	
	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 */
	public void setDescription(String value) {

		this.description = value;
	}
	
	
	
	/**
	 * Gets the value of the id property.
	 */
	public int getId() {

		return id;
	}
	
	
	
	/**
	 * Sets the value of the id property.
	 */
	public void setId(int value) {

		this.id = value;
	}
	
}
