//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b01-EA2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.06 at 06:25:30 PM BST 
//


package es.ull.isaatc.simulation.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SingleFlow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleFlow">
 *   &lt;complexContent>
 *     &lt;extension base="{}Flow">
 *       &lt;sequence>
 *         &lt;element name="act_ref" type="{}ComponentRef"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleFlow", propOrder = {
    "actRef"
})
public class SingleFlow
    extends Flow
{

    @XmlElement(name = "act_ref", required = true)
    protected ComponentRef actRef;

    /**
     * Gets the value of the actRef property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentRef }
     *     
     */
    public ComponentRef getActRef() {
        return actRef;
    }

    /**
     * Sets the value of the actRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentRef }
     *     
     */
    public void setActRef(ComponentRef value) {
        this.actRef = value;
    }

}
