//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.26 at 12:20:59 PM BST 
//


package es.ull.isaatc.simulation.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkGroup">
 *   &lt;complexContent>
 *     &lt;extension base="{}DescComponent">
 *       &lt;sequence>
 *         &lt;element name="role" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rt_ref" type="{}ComponentRef"/>
 *                   &lt;element name="units" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkGroup", propOrder = {
    "role"
})
public class WorkGroup
    extends DescComponent
{

    protected List<WorkGroup.Role> role;

    /**
     * Gets the value of the role property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the role property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkGroup.Role }
     * 
     * 
     */
    public List<WorkGroup.Role> getRole() {
        if (role == null) {
            role = new ArrayList<WorkGroup.Role>();
        }
        return this.role;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rt_ref" type="{}ComponentRef"/>
     *         &lt;element name="units" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rtRef",
        "units"
    })
    public static class Role {

        @XmlElement(name = "rt_ref", required = true)
        protected ComponentRef rtRef;
        protected int units;

        /**
         * Gets the value of the rtRef property.
         * 
         * @return
         *     possible object is
         *     {@link ComponentRef }
         *     
         */
        public ComponentRef getRtRef() {
            return rtRef;
        }

        /**
         * Sets the value of the rtRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link ComponentRef }
         *     
         */
        public void setRtRef(ComponentRef value) {
            this.rtRef = value;
        }

        /**
         * Gets the value of the units property.
         * 
         */
        public int getUnits() {
            return units;
        }

        /**
         * Sets the value of the units property.
         * 
         */
        public void setUnits(int value) {
            this.units = value;
        }

    }

}
